### ISSUE TITLE
[HomeWork] lesson1

### ISSUE THREAD

**Issue by lukashlobil** [lukashlobil/javascript-training#3]
var array = [3, 5, 5, 2, 1, 0, 0, 4]

tasks: checkout an existing branch @Felburg [hwo/lesson1], @Michal [hwm/lesson1] and submit a pull request, where:

there will be a final array called result looking like this [a, b, c, d], where:

- a = sum of all elements' values in the array

- b = lowest value of element in the array

- c = approximate of array's element's values

- d = index of the array's highest value

**Comment by Felburg** [comment]
var array = [3, 5, 5, 2, 1, 0, 0, 4]

var a = 0;
var b = 0;
var c = 0;
var d = 0;

for (var i = 0; i < array.length; i++) {
    a = array[i] + a;
    b = Math.min(...array);
    c = (array[i] + c);
    d = array.reduce((iMax, x, i, array) => x > array[iMax] ? i : iMax);
}

console.log("a = " + a);
console.log("b = " + b);
console.log("c = " + c / array.length);
console.log("d = " + d);

**Comment by Felburg** [comment]
What if **d** has a condition to return **all indexes** with the highest values?

**Desired solution**
Adjust solution to reflect the change and post the output.
